title: Project MURA
description: Página de Project Mura
url: https://Jhoorodre.github.io
baseurl: /project-mura
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
theme: jekyll-theme-primer
plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
collections:
  witchriv:
    output: true
    permalink: /witchriv/:name/
  goldship:
    output: true
    permalink: /goldship/:name/
  hatori-to-furuta:
    output: true
    permalink: /hatori-to-furuta/:name/
  idolatry:
    output: true
    permalink: /idolatry/:name/
  horizon:
    output: true
    permalink: /horizon/:name/
  ending-maker:
    output: true
    permalink: /ending-maker/:name/
  regression-of-the-close-combat-mage:
    output: true
    permalink: /regression-of-the-close-combat-mage/:name/
defaults:
- scope:
    type: witchriv
  values:
    layout: caps
- scope:
    type: goldship
  values:
    layout: caps
- scope:
    type: 100novias
  values:
    layout: caps
- scope:
    type: dream
  values:
    layout: caps
- scope:
    type: idolatry
  values:
    layout: caps
- scope:
    type: hatori-to-furuta
  values:
    layout: caps
- scope:
    type: horizon
  values:
    layout: caps
- scope:
    type: ending-maker
  values:
    layout: caps
- scope:
    type: regression-of-the-close-combat-mage
  values:
    layout: caps
exclude:
- node_modules
- vendor
- README.md
include:
- assets
